language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "tappasarn-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'