import utils.CurrencyFormatter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String amount = args[0];
        String locale = args[1];

        CurrencyFormatter currencyFormatter = new CurrencyFormatter();

        System.out.println(currencyFormatter.format(amount, locale));
    }
}
