import utils.CurrencyFormatter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static String main(String amount, String locale) {
        CurrencyFormatter currencyFormatter = new CurrencyFormatter();

        return currencyFormatter.format(amount, locale);
    }
}
