/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void AppShouldReturnCorrectString() {
        App app = new App();

        String result = app.main("123", "en-US");

        assertEquals("123", result);
    }
}
